---

- name: OSX
  local_action:
    module: osx_say
    msg: "{{ message }}"
    voice: "Samantha"
  when: hostvars['localhost'].ansible_os_family is defined and
        hostvars['localhost'].ansible_os_family == "Darwin"

- name: Slack
  local_action:
    module: slack
    domain: "{{ slack_domain }}"
    msg: "{{ message }}"
    token: "{{ slack_token }}"
    #channel:
  when: with_slack | bool
